
- hosts: localhost
  tasks:
  - name: "create your primary partition "
    parted:
      device: /dev/sdc
      number: 1
      state: present

  - name: "service"
    package:
      name: "scsi-target-utils"
      state: present
  - name: "write in file"
    lineinfile:
      path: "/etc/tgt/targets.conf"
      line: "<target asdfe>"
      insertafter: EOF
  - lineinfile:
      path: "/etc/tgt/targets.conf"
      line: "backing-store /dev/sdc1"
      insertafter: EOF

  - lineinfile:
      path: "/etc/tgt/targets.conf"
      line: "</targets>"
      insertafter: EOF

  - name: "start service"
    service:
       name: tgtd
       state: restarted

- hosts: client
  tasks:
  - command: "iscsiadm --mode discoverydb --type sendtargets --portal 192.168.43.247 --discover"

  - command: "iscsiadm --mode node --targetname asdfe --portal 192.168.43.247:3260 --login"

