
 
- hosts: localhost
  tasks:
  - name: "create your primary partition "
    parted:
      device: /dev/sdb
      number: 1
      state: present
 
  - name: "create a volume group with PE=16MB"
    lvg:
     vg: myvg1
     pvs: /dev/sdb1/
     pesize: 16
     state: present

  - name: " create a logical volume"
    lvol:
      vg: myvg1
      lv: mylv1
      size: "200"
      force: yes

  - name: " format lvm"
    filesystem:
       fstype: "ext4"
       dev: /dev/myvg1/mylv1
       force: yes

  - name: "create folder to mount"
    file:
      path: "asdfee"
      state: directory

  - name: "mount"
    command: "mount /dev/myvg1/mylv1 /root/asdfee"

  - name: "nfs-protocol setup"
    copy:
      content: "/root/asdfee 192.168.43.160(rw,no_root_squash)"
      dest: "/etc/exports"

  - name: "nfs service"
    service:
       name: nfs
       state: restarted
       enabled: yes

- hosts: client
  tasks:
  - name: "make directory"
    file:
      path: "/media/cloudstorage"
      state: directory
  - command: "mount 192.168.43.247:/root/asdfee /media/cloudstorage"

